const cats = [
    { uid: 'NA==', name: 'Watches' },
    { uid: 'MjQ=', name: 'SPORT' },
    { uid: 'Mjk=', name: 'WATCHES SELECTOR' },
    { uid: 'MzA=', name: 'Suggestions' },
    { uid: 'MzE=', name: 'Gift' },
    { uid: 'MzY=', name: "Men's watches" },
    { uid: 'Mzc=', name: "Men's watches" },
    { uid: 'Mzk=', name: "Men's automatic watches" },
    { uid: 'NDQ=', name: 'Movement' },
    { uid: 'NDU=', name: 'Automatic watches' },
    { uid: 'NDY=', name: 'Chronograph watches' },
    { uid: 'NTA=', name: 'Watches' },
    { uid: 'NTE=', name: 'Sports watches' },
    { uid: 'NjY=', name: 'LONGINES SPIRIT' },
    { uid: 'MTE4', name: 'AVIGATION' },
    { uid: 'MjM2', name: 'おすすめセレクション' },
    { uid: 'MjQ5', name: 'All New Product Japan' },
    { uid: 'MzYy', name: 'Gift Finder' },
    { uid: 'Mzc3', name: 'Frohe festtage (DE)' },
    { uid: 'Mzgz', name: 'Frohe festtage (DE-CH)' },
    { uid: 'Mzg2', name: 'Seasons greetings (EN-GB)' },
    { uid: 'Mzg5', name: 'Joyeuses fêtes (FR-CH)' },
    { uid: 'Mzky', name: 'Buone feste (IT-CH)' },
    { uid: 'Mzk3', name: 'Seasons greetings (EN-DK)' },
    { uid: 'NDAw', name: 'Seasons greetings (EN-NO)' },
    { uid: 'NDAz', name: 'Seasons greetings (EN-FI)' },
    { uid: 'NDA2', name: 'Seasons greetings (EN-SE)' },
    { uid: 'NDA5', name: 'Seasons greetings (EN-NL)' },
    { uid: 'NDEy', name: 'Prettige Feestdagen (NL)' },
    { uid: 'NDE1', name: 'Prettige Feestdagen (NL-BE)' },
    { uid: 'NDE4', name: 'Joyeuses fêtes (FR-BE)' },
    { uid: 'NDIx', name: 'Felices fiestas' },
    { uid: 'NDI0', name: 'Wesołych Świąt' },
    { uid: 'NTAz', name: 'Chronometer watches' },
    { uid: 'NTA5', name: "Happy Father's Day CA" },
    { uid: 'NTI3', name: 'Longines Spirit Flyback' },
    { uid: 'MjE4', name: 'Straps' },
    { uid: 'MzUz', name: 'Straps' },
    { uid: 'MzU2', name: 'Nato' },
    { uid: 'MjM5', name: "Valentine's Day Selection" },
    { uid: 'MjY0', name: 'Watches Configurator' },
    { uid: 'Mjcw', name: "Men's sport watches" },
    { uid: 'NDQ5', name: "Valentine's Day Selection" },
    { uid: 'NDU4', name: "Valentine's Day Selection" },
    { uid: 'NDY0', name: "Valentine's Day Selection" },
    { uid: 'NDk2', name: "Happy Father's Day" },
    { uid: 'NTA2', name: "Happy Father's Day US" },
    { uid: 'NTE5', name: 'Longines Spirit Zulu Time 39' },
    { uid: 'ODQ=', name: 'Heritage' },
    { uid: 'ODc=', name: 'Eyewear' },
    { uid: 'ODU=', name: 'Sport' },
    { uid: 'MTU=', name: 'TRADITION' },
    { uid: 'MTc=', name: 'THE LONGINES MASTER COLLECTION' },
    { uid: 'MzI=', name: 'Gift watches' },
    { uid: 'MzQ=', name: 'Gift men watches' },
    { uid: 'NDg=', name: 'Moonphase watches' },
    { uid: 'NTM=', name: 'Steel watches' },
    { uid: 'NjU=', name: 'CLASSIC' },
    { uid: 'MTA0', name: 'The Watchmaking excellence' },
    { uid: 'MTA1', name: 'Quintessence of classicism' },
    { uid: 'MTE1', name: 'Graduation Gifts' },
    { uid: 'NDQw', name: "Valentine's Day Selection" },
    { uid: 'NDUy', name: "Valentine's Day Selection" },
    { uid: 'OTM=', name: 'Festive Selection US' },
    { uid: 'OTc=', name: 'Festive Selection DE' },
    { uid: 'MTAx', name: 'Bridal' },
    { uid: 'MTEy', name: 'The Daily USA' },
    { uid: 'MTE0', name: 'Wedding Gifts USA' },
    { uid: 'MTMw', name: "Father's Day Gift Guide USA" },
    { uid: 'MjMw', name: "Men's watches" },
    { uid: 'MjUy', name: 'Best Seller Japan' },
    { uid: 'NDM0', name: "Valentine's Day Selection" },
    { uid: 'NTEy', name: "Happy Father's Day JP" },
    { uid: 'NTIx', name: "Happy Father's Day AU" },
    { uid: 'NDA=', name: "Women's watches" },
    { uid: 'NDM=', name: "Women's automatic watches" },
    { uid: 'NTQ=', name: 'Classic watches' },
    { uid: 'NTc=', name: 'Category test' },
    { uid: 'MTA3', name: 'Diamond watches' },
    { uid: 'MjEy', name: "Women's watches" },
    { uid: 'NTAw', name: 'Styled in blue' },
    { uid: 'MjU=', name: 'HYDROCONQUEST' },
    { uid: 'MzU=', name: 'Dive watches' },
    { uid: 'MTIy', name: 'DIVING' },
    { uid: 'NTI0', name: 'Hydroconquest GMT' },
    { uid: 'ODM=', name: 'Classic' },
    { uid: 'NDI4', name: "Valentine's Day Selection" },
    { uid: 'MTAz', name: 'Colourful watches' },
    { uid: 'MjY=', name: 'CONQUEST' },
    { uid: 'Mzg=', name: "Men's quartz watches" },
    { uid: 'NDc=', name: 'Quartz watches' },
    { uid: 'NjE=', name: "Father's Day" },
    { uid: 'ODk=', name: "Sélection d'idées cadeaux" },
    { uid: 'MTI2', name: 'PERFORMANCE' },
    { uid: 'NTk=', name: 'Longines timepieces for men' },
    { uid: 'NQ==', name: 'ELEGANCE' },
    { uid: 'Nw==', name: 'LONGINES DOLCEVITA' },
    { uid: 'MzM=', name: 'Gift women watches' },
    { uid: 'NDI=', name: "Women's quartz watches" },
    { uid: 'NjA=', name: 'Longines Timepieces for women' },
    { uid: 'OTY=', name: 'Festive Selection JP' },
    { uid: 'MjI3', name: 'Test category' },
    { uid: 'MjMz', name: "Women's watches" },
    { uid: 'Mjcz', name: "Women's sports watches" },
    { uid: 'OTU=', name: 'Festive Selection CH' },
    { uid: 'MTIz', name: 'LONGINES LEGEND DIVER' },
    { uid: 'OTQ=', name: 'Selezione per le feste' },
    { uid: 'MTE3', name: 'HERITAGE CLASSIC' },
    { uid: 'MjE1', name: 'Heritage Inspired US ' },
    { uid: 'MzY1', name: 'HYDROCONQUEST SPECIAL' },
    { uid: 'Ng==', name: 'LONGINES PRIMALUNA' },
    { uid: 'NDQ2', name: "Valentine's Day Selection" },
    { uid: 'NDkz', name: "Happy Mother's Day TW" },
    { uid: 'Mzk1', name: 'Joyeuses fêtes (FR)' },
    { uid: 'MTIw', name: 'HERITAGE AVIGATION' },
    { uid: 'NDMx', name: "Valentine's Day Selection" },
    { uid: 'MTI5', name: 'LONGINES ULTRA‑CHRON' },
    { uid: 'NjM=', name: 'LA GRANDE CLASSIQUE DE LONGINES' },
    { uid: 'NDM3', name: "Valentine's Day Selection" },
    { uid: 'MTM=', name: 'FLAGSHIP' },
    { uid: 'MjE=', name: 'RECORD' },
    { uid: 'NDY3', name: "Valentine's Day Selection" },
    { uid: 'NDg0', name: "Happy Mother's Day GR" },
    { uid: 'MjA=', name: 'LONGINES EVIDENZA' },
    { uid: 'NDcy', name: "Happy Mother's Day" },
    { uid: 'NDc1', name: "Happy Mother's Day US" },
    { uid: 'MTY=', name: 'THE LONGINES ELEGANT COLLECTION' },
    { uid: 'OTA=', name: 'Winter Wonders Selection UK' },
    { uid: 'NDc4', name: "Happy Mother's Day CA" },
    { uid: 'NDI1', name: "Valentine's Day Selection" },
    { uid: 'NDU1', name: "Valentine's Day Selection" },
    { uid: 'NDYx', name: "Valentine's Day Selection" },
    { uid: 'NDgx', name: "Happy Mother's Day AU" },
    { uid: 'NDg3', name: "Happy Mother's Day JP" },
    { uid: 'NDkw', name: "Happy Mother's Day ES" },
    { uid: 'MTg=', name: 'CONQUEST CLASSIC' },
    { uid: 'OTE=', name: 'Festive Selection AU' },
    { uid: 'NTI=', name: 'Gold watches' },
    { uid: 'NDQz', name: "Valentine's Day Selection" },
    { uid: 'NDk=', name: 'Retrograde watches' },
    { uid: 'OTk=', name: 'LONGINES HOLIDAY SHOPPING EVENT' },
];
module.exports = cats;